apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {? {.Values.name | default "pharmacy-app": ''} : ''}
  name: {? {.Values.sqlserver.service.name: 'back-end'} : ''}
  labels:
    component: back-end
spec:
  replicas: {? {.Values.backEnd.replicaCount: ''} : ''}
  selector:
    matchLabels:
      component: back-end
  template:
    metadata:
      labels:
        component: back-end
    spec:
      containers:
      - name: back-end
        image: "{{ .Values.backEnd.image.repository }}:{{ .Values.backEnd.image.tag }}"
        ports:
        - containerPort: {? {.Values.backEnd.service.port: ''} : ''}
          name: {? {.Values.backEnd.service.name: ''} : ''}
        resources:
          requests:
            cpu: "{{ .Values.backEnd.resources.requests.cpu }}"
            memory: "{{ .Values.backEnd.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.backEnd.resources.limits.cpu }}"
            memory: "{{ .Values.backEnd.resources.limits.memory }}"
      imagePullSecrets:
      - name: {? {.Values.backEnd.imagePullSecrets.name: ''} : ''}
