apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backEnd.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.backEnd.name }}
spec:
  replicas: {{ .Values.backEnd.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backEnd.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backEnd.name }}
    spec:
      containers:
        - name: {{ .Values.backEnd.name }}
          image: {{ .Values.backEnd.image.repository }}:{{ .Values.backEnd.image.tag }}
          imagePullPolicy: {{ .Values.backEnd.image.pullPolicy }}
          ports:
            - name: http-backend
              containerPort: {{ .Values.backEnd.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.backEnd.resources.requests.cpu }}
              memory: {{ .Values.backEnd.resources.requests.memory }}
            limits:
              cpu: {{ .Values.backEnd.resources.limits.cpu }}
              memory: {{ .Values.backEnd.resources.limits.memory }}
      imagePullSecrets:
        - name: {{ .Values.backEnd.imagePullSecrets.name }}