apiVersion: v1
kind: Service
metadata:
  namespace: {? {.Values.namespace: ''} : ''}
  name: {? {.Values.sqlserver.service.name: ''} : ''}
  labels:
    component: sqlserver
spec:
  selector:
    component: sqlserver
  ports:
  - port: {? {.Values.sqlserver.service.port: ''} : ''}
