apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.certManager.issuer.name }}
  namespace: {{ .Values.certManager.issuer.namespace }}
spec:
  acme:
    email: {{ .Values.certManager.issuer.email }}
    server: {{ .Values.certManager.issuer.server }}
    privateKeySecretRef:
      name: {{ .Values.certManager.issuer.privateKeySecretName }}
    solvers:
    {{- range .Values.certManager.issuer.solvers }}
    - http01:
        ingress:
          class: {{ .http01.ingressClass }}
    {{- end }}