apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Name }}-resource-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.cpuRequests }}
    requests.memory: {{ .Values.resourceQuota.memoryRequests }}
    limits.cpu: {{ .Values.resourceQuota.cpuLimits }}
    limits.memory: {{ .Values.resourceQuota.memoryLimits }}