{{- if .Values.secrets }}
{{- range .Values.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{- range $key, $value := .encryptedData }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sqlserver.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MSSQL_SA_PASSWORD: {{ .Values.sqlserver.secret.MSSQL_SA_PASSWORD }}
{{- end }}
