apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sqlserver.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MSSQL_SA_PASSWORD: {{ .Values.sqlserver.secret.MSSQL_SA_PASSWORD }}