apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backEnd.service.name | default "" }}
  namespace: {{ .Values.namespace | default "" }}
spec:
  type: {{ .Values.backEnd.service.type | default "" }}
  ports:
  - port: {{ .Values.backEnd.service.port | default 0 }}
    targetPort: {{ .Values.backEnd.service.targetPort | default 0 }}
    protocol: TCP
  selector:
    app: {{ .Values.backEnd.name | default "" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontEnd.service.name | default "" }}
  namespace: {{ .Values.namespace | default "" }}
spec:
  type: {{ .Values.frontEnd.service.type | default "" }}
  ports:
  - port: {{ .Values.frontEnd.service.port | default 0 }}
    targetPort: {{ .Values.frontEnd.service.targetPort | default 0 }}
    protocol: TCP
  selector:
    app: {{ .Values.frontEnd.name | default "" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sqlserver.service.name | default "" }}
  namespace: {{ .Values.namespace | default "" }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.sqlserver.service.port | default 0 }}
  selector:
    app: {{ .Values.sqlserver.service.name | default "" }}
