namespace: myapp

backEnd:
  replicaCount: 2
  name: back-end
  image:
    repository: datnd2711/pharmacy-be
    tag: prod-0.92
    pullPolicy: IfNotPresent
  imagePullSecrets:
    name: my-dockerhub-secret
  service:
    name: back-end-service
    type: ClusterIP
    port: 8080
    targetPort: "http-backend" # Tên cổng cụ thể
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontEnd:
  replicaCount: 2
  name: front-end
  image:
    repository: datnd2711/pharmacy-fe
    tag: prod-0.112
    pullPolicy: IfNotPresent
  imagePullSecrets:
    name: my-dockerhub-secret
  service:
    name: front-end-service
    type: ClusterIP
    port: 80
    targetPort: "http-frontend" # ensure this is an integer
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

sqlserver:
  image:
    repository: datnd2711/sqlserver
    tag: prod-0.72
    pullPolicy: IfNotPresent
  imagePullSecrets:
    name: my-dockerhub-secret
  service:
    name: sqlserver
    port: 1433
  resources:
    requests:
      cpu: "250m"
      memory: "500m"
    limits:
      cpu: "0.5"
      memory: "1Gi"
  volume:
    storageClassName: nfs-retain
    size: 3Gi
  secret:
    name: sqlserver-secret
    MSSQL_SA_PASSWORD: RGF0TGFpZDIzNDU1NUBYeQ==  
    # using bitnami sealed secret
    # MSSQL_SA_PASSWORD: AgANrD5nld3z5i/GX8T4hy0va08NtZYS9hiuvMRN58FVgwR8TuwWhK/MC1qccUfIG1QO7SnkIkEDGh3+/3dg330UXaRZii3ORPuLd/j6FvAndg1y8R/AEQm/i58DQasjYy9tbhJOvCTqnon49a8NVKI3bZimrK2Xiue0Wk88zVe05PnBb2eBInn5vDTspyY8CjVz6brH46CESwxAbaR6y65AhPf7gwVegbNh13tH9maiW91w4IFSTwOAeqpXM1WSTPtkyyWpBk3zkmhZuY3Qb5v11zBT7j576b0IXhY2d47EoUAlDTYdW4np1Yn1jazkAGTpmP8TGvaf+IwOn82Y8hB2q4qsZThQRBNtFvfjkI4h8rGveYstV++nHOm0tslodqEdTjVmZviJT+ox+/RACDtnOM6ipNCzq9pclnRHTQO/me4zlB+tzpIFLxRYBSD/eCgbdq/8knb1ZDr3murqjhX5dFEE/MnAASCiL5090MChw1AHHCBjUm/wxUajrki5eAtKC5EY7WELo8YNBV3CSVaGvJ4Q5cf0SMLkXOLoHP09Ay54twAHxnUViJCY0zl6EGU6opn5MJ1nkfz7ThY8uYnN0r3+YJ61Q9ZE1IzwJETIs4LQMOTAgE5L0ZvBbNQzuFXKkdyU8ggl1LE0RJIoIXD4tZkeIYgBDXQMMojQCC7icMN76Il9cmqvqHUOSPoSl0VVT8jLbSt9OGeA74d9448o
    # command: ["/bin/bash", "-c"]
# args: ["/dbconfig/attach.sh && /opt/mssql/bin/sqlservr && tail -f /dev/null"]


ingress:
  name: pharmacy-ingress
  annotations:
    # cert-manager.io/cluster-issuer: "ca-issuer"
    # kubernetes.io/ingress.class: "nginx"
  ingressClassName: nginx
    # tls:
    # - hosts:
    # - demo.datlaid.com
    # secretName: ssl-demo.datlaid.com
  rules:
  - host: demo.datlaid.com
    paths:
    - path: /
      pathType: Prefix
      frontend:
        serviceName: front-end-service
        servicePort: http-frontend
    - path: /api
      pathType: Prefix
      backend:
        serviceName: back-end-service
        servicePort: http-backend

 
hpa:
  enabled: true
  name: autoscale-hpa
  namespace: test-helm
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-end
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 3
      - type: Percent
        value: 50
        periodSeconds: 60
      stabilizationWindowSeconds: 200


resourceQuota:
  cpuRequests: "1.5"
  memoryRequests: "2.5Gi"
  cpuLimits: "3"
  memoryLimits: "5Gi"
  
service:
  port: "8080"
