apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: pharmacy-app
  name: sqlserver
  labels:
    component: sqlserver
spec:
  selector:
    matchLabels:
      component: sqlserver
  serviceName: sqlserver
  template:
    metadata:
      labels:
        component: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: datnd2711/sqlserver:v16
        ports:
        - containerPort: 1433
        volumeMounts:
        - mountPath: /var/opt/mssql/data
          name: sqlserver-data
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        env:
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: MSSQL_SA_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
        command: ["/bin/bash", "-c"]
        args:
        - "/dbconfig/attach.sh && /opt/mssql/bin/sqlservr && tail -f /dev/null"
      imagePullSecrets:
      - name: my-dockerhub-secret
  volumeClaimTemplates:
  - metadata:
      name: sqlserver-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: nfs-client
      resources:
        requests:
          storage: 3Gi
