apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: pharmacy-app
  name: sqlserver
  labels:
    component: sqlserver
spec:
  selector:
    matchLabels:
      component: sqlserver
  serviceName: sqlserver
  template:
    metadata:
      labels:
        component: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: datnd2711/sqlserver:v19
        ports:
        - containerPort: 1433
        volumeMounts:
        - mountPath: /var/opt/mssql/data
          name: sqlserver-data
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        env:
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: MSSQL_SA_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
        command: ["/bin/bash", "-c"]
        args:
        - "/dbconfig/attach.sh && /opt/mssql/bin/sqlservr && tail -f /dev/null"
        livenessProbe:
          exec:
            # command:
            # ["/bin/bash", "-c", "/dbconfig/health_check.sh"]
            # - /bin/bash
            # - -c
            # - "/dbconfig/health_check.sh"
            command: ["/bin/bash", "-c", " /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P DatLaid234555@Xy -Q 'SELECT 1'"]

          initialDelaySeconds: 45
          periodSeconds: 10
          failureThreshold: 4
        readinessProbe:
          exec:
            # command:
            # ["/bin/bash", "-c", "/dbconfig/health_check.sh"]
            # - /bin/bash
            # - -c
            # - "/dbconfig/health_check.sh"
            command: ["/bin/bash", "-c", " /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P DatLaid234555@Xy -Q 'SELECT 1'"]

          initialDelaySeconds: 45
          periodSeconds: 10
          failureThreshold: 4
      imagePullSecrets:
      - name: my-dockerhub-secret
  volumeClaimTemplates:
  - metadata:
      name: sqlserver-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: nfs-client
      resources:
        requests:
          storage: 3Gi
