apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscale-hpa
  namespace: pharmacy-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-end
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 3
      - type: Percent
        value: 50
        periodSeconds: 60
      stabilizationWindowSeconds: 200

