apiVersion: v1
kind: ResourceQuota
metadata:
  name: pharmacy-app-quota
  namespace: pharmacy-app
spec:
  hard:
    requests.cpu: "1.5" # Tổng yêu cầu CPU từ StatefulSet (1) + Deployment (0.5)
    requests.memory: "2.5Gi" # Tổng yêu cầu bộ nhớ từ StatefulSet (2Gi) + Deployment (512Mi)
    limits.cpu: "3" # Tổng giới hạn CPU từ StatefulSet (2) + Deployment (1)
    limits.memory: "5Gi" # Tổng giới hạn bộ nhớ từ StatefulSet (4Gi) + Deployment (1Gi)
