{{- define "shared-chart.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.type | default "ClusterIP" }}
  ports:
    - name: {{ .Values.name }}
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort | default .Values.port }}
      protocol: TCP
  selector:
    app: {{ .Values.name }}
{{- end -}}
